### ISSUE TITLE
Link Broken Lab

### ISSUE THREAD

**Issue by hannespreishuber** [microsoftgraph/msgraph-training-authentication#4]
Lab Manual Link is broken
overall i need a walkthrough 

creating a Task in Planner from ASP.NET Website

**Comment by andrewconnell** [comment]
Looks like a typo in the link... gotta love case-sensitive links! We'll get it fixed, but until then: https://github.com/microsoftgraph/msgraph-training-authentication/blob/master/lab.md

This module does not cover creating tasks in Planner with the Microsoft Graph. However, here's a link to the docs on that topic (not a walkthrough): https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/planner_post_tasks
